spring:
  #H2 ?????? ??
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #Queyr? ?? ??? ???
        use_sql_comments: true #Queyr? ??

logging:
  level:
    org.hibernate.sql: debug

server:
  port: 8081
